/* =========================================================================
   Mon Petit Coin de Bretagne — données du guide « Découvrir la Bretagne »
   -------------------------------------------------------------------------
   Toutes les informations factuelles (adresses, sites officiels, nature des
   lieux) proviennent de recherches vérifiées (sites officiels, offices de
   tourisme, sources institutionnelles — voir le champ `website`).
   Les distances et temps de trajet sont des ESTIMATIONS routières depuis
   Mon Petit Coin de Bretagne (15 route de la Croizetière, 56670 Riantec) —
   à confirmer avec votre GPS le jour J. Les horaires et tarifs, sujets à
   changement, ne sont volontairement PAS détaillés ici : chaque fiche
   renvoie vers le site officiel du lieu pour l'information à jour.

   Pour ajouter / modifier / supprimer une activité : éditez simplement le
   tableau ACTIVITIES ci-dessous, chaque entrée suit le même schéma.
   ========================================================================= */

const CATEGORIES = [
  { slug: "incontournables", label: "Nos incontournables", icon: "star" },
  { slug: "mer",             label: "Mer & plages",         icon: "wave" },
  { slug: "balades",         label: "Balades & randonnées", icon: "path" },
  { slug: "patrimoine",      label: "Patrimoine & culture", icon: "landmark" },
  { slug: "sorties-mer",     label: "Sorties en mer",       icon: "boat" },
  { slug: "famille",         label: "En famille",           icon: "family" },
  { slug: "sport",           label: "Sport & nature active",icon: "bike" },
  { slug: "nature",          label: "Nature & jardins",     icon: "leaf" },
  { slug: "pluie",           label: "Quand il pleut",       icon: "umbrella" }
];

/* Chaque activité :
   id, name, categories[] (slugs ci-dessus), description, distance, driveTime,
   duration, tags[] (mots-clés recherche + moteur "Que faire aujourd'hui"),
   accent (jeton couleur CSS), icon, address, website, bookingRequired
   (true|false|"à vérifier"), price (texte prudent ou null), featured (bool,
   = "incontournable"), heart (bool, = coup de cœur d'Emmanuelle), tip (texte
   court, uniquement pour les coups de cœur). */
const ACTIVITIES = [
  {
    id: "petite-mer-gavres",
    name: "La Petite Mer de Gâvres",
    categories: ["mer", "balades", "nature", "famille"],
    description: "Une lagune abritée entre Riantec et Gâvres, bordée d'un sentier de balade au calme — le premier bol d'air à deux pas de la maison.",
    distance: "≈ 700 m",
    driveTime: "10 min à pied",
    duration: "1h à 1h30",
    tags: ["mer", "plage", "balade", "nature", "famille", "calme", "2h", "detente"],
    accent: "ocean",
    icon: "wave",
    address: "Riantec / Gâvres, 56670",
    website: null,
    bookingRequired: false,
    price: null,
    featured: false,
    heart: true,
    tip: "Notre conseil : partez en fin de journée, la lumière sur l'eau y est particulièrement belle."
  },
  {
    id: "grande-plage-port-louis",
    name: "Grande Plage de Port-Louis",
    categories: ["mer", "famille", "sport"],
    description: "Une grande plage de sable face à la rade de Lorient, facilement accessible, idéale pour une après-midi baignade en famille.",
    distance: "≈ 2,7 km",
    driveTime: "5 min en voiture",
    duration: "Demi-journée",
    tags: ["mer", "plage", "famille", "baignade", "demi-journee", "sport"],
    accent: "ocean",
    icon: "wave",
    address: "Port-Louis, 56290",
    website: "https://morbihan.com",
    bookingRequired: false,
    price: null,
    featured: false,
    heart: false,
    tip: null
  },
  {
    id: "citadelle-port-louis",
    name: "Citadelle de Port-Louis",
    categories: ["patrimoine", "incontournables", "famille", "pluie"],
    description: "Forteresse du XVIIe siècle fermant l'entrée de la rade de Lorient, abritant le Musée national de la Marine et le Musée de la Compagnie des Indes.",
    distance: "≈ 1,5 km",
    driveTime: "5 min en voiture",
    duration: "2h à 3h",
    tags: ["patrimoine", "culture", "musee", "famille", "pluie", "demi-journee", "incontournable"],
    accent: "sand",
    icon: "landmark",
    address: "Citadelle, 56290 Port-Louis",
    website: "https://www.musee-marine.fr/nos-musees/port-louis.html",
    bookingRequired: false,
    price: "Indicatif : plein tarif ≈ 10 €, réduit ≈ 8 € — tarifs et horaires à jour sur le site officiel.",
    featured: true,
    heart: true,
    tip: "Notre conseil : comptez une bonne demi-journée pour les deux musées, il y a beaucoup à voir."
  },
  {
    id: "cite-voile-tabarly",
    name: "Cité de la Voile Éric Tabarly",
    categories: ["patrimoine", "famille", "pluie", "sport"],
    description: "Espace muséographique dédié à la voile de compétition et à Éric Tabarly, sur le site de Lorient La Base — expositions interactives, simulateur, sorties en mer possibles.",
    distance: "≈ 15 km",
    driveTime: "20 min en voiture",
    duration: "2h",
    tags: ["patrimoine", "musee", "famille", "pluie", "sport", "voile"],
    accent: "navy",
    icon: "boat",
    address: "Lorient La Base, 56100 Lorient",
    website: "https://www.citevoile-tabarly.com",
    bookingRequired: false,
    price: "Tarifs sur le site officiel.",
    featured: false,
    heart: false,
    tip: null
  },
  {
    id: "base-keroman",
    name: "Base des sous-marins de Keroman",
    categories: ["patrimoine", "pluie", "famille"],
    description: "Ancienne base sous-marine allemande de la Seconde Guerre mondiale, aujourd'hui ouverte à la visite au cœur de Lorient La Base — un lieu d'histoire impressionnant, quel que soit le temps.",
    distance: "≈ 15 km",
    driveTime: "20 min en voiture",
    duration: "1h30",
    tags: ["patrimoine", "histoire", "pluie", "famille"],
    accent: "slate",
    icon: "landmark",
    address: "Lorient La Base, 56100 Lorient",
    website: "https://patrimoine.lorient.bzh/histoire/architecture/edifices-militaires/base-de-sous-marins-de-keroman/",
    bookingRequired: false,
    price: null,
    featured: false,
    heart: false,
    tip: null
  },
  {
    id: "hennebont",
    name: "Hennebont, cité médiévale",
    categories: ["patrimoine", "balades"],
    description: "Ville close du XIIIe siècle sur les bords du Blavet : remparts, basilique Notre-Dame-de-Paradis, et le plus grand marché de Bretagne le jeudi matin.",
    distance: "≈ 20 km",
    driveTime: "25 min en voiture",
    duration: "Demi-journée",
    tags: ["patrimoine", "balade", "marche", "demi-journee"],
    accent: "sand",
    icon: "landmark",
    address: "Hennebont, 56700",
    website: "https://www.lorientbretagnesudtourisme.fr/fr/immanquables/hennebont/",
    bookingRequired: false,
    price: null,
    featured: false,
    heart: false,
    tip: null
  },
  {
    id: "fort-bloque",
    name: "Fort-Bloqué (Ploemeur)",
    categories: ["mer", "nature", "famille", "sport"],
    description: "Un îlot fortifié relié à la plage à marée basse, entre dunes et longue plage de sable — spot connu pour le char à voile et le surf.",
    distance: "≈ 15 km",
    driveTime: "20 min en voiture",
    duration: "2h à demi-journée",
    tags: ["mer", "plage", "sport", "famille", "nature", "surf"],
    accent: "ocean",
    icon: "wave",
    address: "Boulevard de l'Océan, 56270 Ploemeur",
    website: "https://www.ploemeur.com/en/decouvrir/les-plages/fort-bloque/",
    bookingRequired: false,
    price: null,
    featured: false,
    heart: true,
    tip: "Notre conseil : à marée basse, on rejoint le fort à pied — un vrai moment suspendu."
  },
  {
    id: "ile-de-groix",
    name: "Île de Groix",
    categories: ["sorties-mer", "nature", "incontournables", "sport"],
    description: "1 500 hectares entre falaises sauvages et criques, à 45 minutes de bateau de Lorient — idéale à parcourir à vélo pour la journée.",
    distance: "≈ 15 km jusqu'au port de Lorient, puis 45 min de traversée",
    driveTime: "20 min + bateau",
    duration: "Journée",
    tags: ["sorties-mer", "bateau", "nature", "sport", "velo", "journee", "incontournable"],
    accent: "moss",
    icon: "boat",
    address: "Départ Lorient — Port-Tudy, Île de Groix",
    website: "https://oceane.breizhgo.bzh",
    bookingRequired: true,
    price: "Traversée avec BreizhGo Océane — tarifs et horaires sur le site officiel.",
    featured: true,
    heart: true,
    tip: "Notre conseil : réservez la traversée à l'avance en été, les départs se remplissent vite."
  },
  {
    id: "carnac",
    name: "Carnac & les alignements mégalithiques",
    categories: ["patrimoine", "incontournables", "famille"],
    description: "Le plus grand ensemble mégalithique au monde, vieux de 6 000 ans. La Maison des Mégalithes (Centre des monuments nationaux) accueille et guide les visiteurs.",
    distance: "≈ 35 km",
    driveTime: "40 min en voiture",
    duration: "2h à demi-journée",
    tags: ["patrimoine", "megalithes", "famille", "demi-journee", "incontournable"],
    accent: "sand",
    icon: "landmark",
    address: "Maison des Mégalithes, route des Alignements, 56340 Carnac",
    website: "https://www.menhirs-carnac.fr",
    bookingRequired: "Visite guidée obligatoire d'avril à septembre ; accès libre le reste de l'année (voir site officiel).",
    price: "Tarifs sur le site officiel.",
    featured: true,
    heart: true,
    tip: "Notre conseil : hors saison (octobre à mars), on peut flâner librement entre les menhirs — un moment à part."
  },
  {
    id: "quiberon",
    name: "Quiberon & la Côte Sauvage",
    categories: ["mer", "nature", "sport", "incontournables"],
    description: "Une presqu'île de 14 km bordée par une côte sauvage aux falaises spectaculaires sur 8 km, et l'embarcadère vers Belle-Île.",
    distance: "≈ 50 km",
    driveTime: "1h en voiture",
    duration: "Journée",
    tags: ["mer", "plage", "nature", "sport", "randonnee", "journee", "incontournable"],
    accent: "ocean",
    icon: "wave",
    address: "Quiberon, 56170",
    website: "https://www.quiberon.com",
    bookingRequired: false,
    price: null,
    featured: true,
    heart: false,
    tip: null
  },
  {
    id: "golfe-morbihan-vannes",
    name: "Vannes & le Golfe du Morbihan",
    categories: ["patrimoine", "sorties-mer", "incontournables", "famille"],
    description: "Ville d'Art et d'Histoire aux remparts préservés, porte d'entrée du Golfe du Morbihan — membre du club des Plus Belles Baies du Monde.",
    distance: "≈ 45 km",
    driveTime: "50 min en voiture",
    duration: "Journée",
    tags: ["patrimoine", "sorties-mer", "famille", "journee", "incontournable"],
    accent: "sand",
    icon: "landmark",
    address: "Vannes, 56000",
    website: "https://www.golfedumorbihan.bzh",
    bookingRequired: false,
    price: null,
    featured: true,
    heart: true,
    tip: "Notre conseil : garez-vous côté port et laissez-vous simplement porter dans les ruelles de la vieille ville."
  },
  {
    id: "izenah-croisieres",
    name: "Croisière dans le Golfe du Morbihan",
    categories: ["sorties-mer", "famille"],
    description: "Balades commentées en bateau parmi les îles du Golfe (Île aux Moines, Île d'Arz), au départ de Baden ou Larmor-Baden.",
    distance: "≈ 50 km jusqu'au départ",
    driveTime: "1h en voiture",
    duration: "1h30 à demi-journée",
    tags: ["sorties-mer", "bateau", "famille", "demi-journee"],
    accent: "navy",
    icon: "boat",
    address: "Départ Baden / Larmor-Baden",
    website: "https://www.izenah-croisieres.com",
    bookingRequired: true,
    price: "Réservation conseillée — tarifs sur le site officiel.",
    featured: false,
    heart: false,
    tip: null
  },
  {
    id: "belle-ile",
    name: "Belle-Île-en-Mer",
    categories: ["sorties-mer", "nature", "incontournables"],
    description: "La plus grande des îles bretonnes, accessible en 45 minutes de bateau depuis Quiberon — falaises, aiguilles de Port-Coton, criques et villages de charme.",
    distance: "≈ 50 km jusqu'à l'embarcadère de Quiberon, puis 45 min de traversée",
    driveTime: "1h + bateau",
    duration: "Journée entière (voire plus)",
    tags: ["sorties-mer", "bateau", "nature", "journee", "incontournable"],
    accent: "moss",
    icon: "boat",
    address: "Départ Quiberon (Port-Maria) — Le Palais, Belle-Île",
    website: "https://www.belle-ile.com",
    bookingRequired: true,
    price: "Traversée avec BreizhGo Océane — tarifs et horaires sur le site officiel.",
    featured: true,
    heart: false,
    tip: null
  },
  {
    id: "festival-interceltique",
    name: "Festival Interceltique de Lorient",
    categories: ["patrimoine", "incontournables"],
    description: "Chaque année, sur une dizaine de jours à cheval sur fin juillet et début août, Lorient devient la capitale mondiale des cultures celtes : grande parade des nations, concerts et pavillons des pays invités.",
    distance: "≈ 15 km",
    driveTime: "20 min en voiture",
    duration: "Une journée ou plus (festival de 10 jours)",
    tags: ["festival", "musique", "celtique", "concert", "aout", "juillet", "ete", "incontournable", "journee"],
    accent: "navy",
    icon: "star",
    address: "Lorient, 56100",
    website: "https://www.festival-interceltique.bzh",
    bookingRequired: "Billetterie conseillée pour les concerts et spectacles — parade et animations de rue accessibles librement. Voir le site officiel.",
    price: "Tarifs sur le site officiel selon les spectacles.",
    featured: true,
    heart: true,
    tip: "Notre conseil : réservez votre séjour et vos billets de concert plusieurs mois à l'avance, c'est l'un des plus grands festivals de France."
  },
  {
    id: "saint-goustan-auray",
    name: "Saint-Goustan (Auray)",
    categories: ["patrimoine", "balades", "incontournables"],
    description: "Le quartier historique du port d'Auray : pont médiéval, maisons à pans de bois et quai Benjamin Franklin, du nom de l'ambassadeur américain qui y débarqua en 1776.",
    distance: "≈ 35 km",
    driveTime: "40 min en voiture",
    duration: "2h à demi-journée",
    tags: ["patrimoine", "balade", "port", "demi-journee"],
    accent: "sand",
    icon: "landmark",
    address: "Saint-Goustan, 56400 Auray",
    website: "https://morbihan.com/decouvrir/le-morbihan-et-ses-perles-bretonnes/destination-carnac-et-baie-de-quiberon/auray-saint-goustan/",
    bookingRequired: false,
    price: null,
    featured: false,
    heart: true,
    tip: "Notre conseil : flânez le long du quai en fin de journée, quand les terrasses s'animent."
  },
  {
    id: "concarneau-ville-close",
    name: "Concarneau — la Ville Close",
    categories: ["patrimoine", "mer"],
    description: "Une ville fortifiée du XIVe siècle bâtie sur un îlot au cœur du port de pêche, aux portes du Finistère — ruelles pavées, remparts et crêperies, facile à combiner avec Pont-Aven.",
    distance: "≈ 70 km",
    driveTime: "1h10 en voiture",
    duration: "Demi-journée",
    tags: ["patrimoine", "ville-close", "port", "demi-journee", "journee"],
    accent: "sand",
    icon: "landmark",
    address: "Ville Close, 29900 Concarneau",
    website: "https://www.deconcarneauapontaven.com/explorer/vacances-de-concarneau-a-pont-aven/visiter-concarneau/",
    bookingRequired: false,
    price: null,
    featured: false,
    heart: false,
    tip: null
  },
  {
    id: "pont-aven",
    name: "Pont-Aven, la cité des peintres",
    categories: ["patrimoine"],
    description: "Le petit port qui a vu naître l'école de peinture de Gauguin, entre moulins à eau, galeries d'art et sentier du Bois d'Amour — à quelques minutes de Concarneau.",
    distance: "≈ 80 km",
    driveTime: "1h20 en voiture",
    duration: "Demi-journée",
    tags: ["patrimoine", "art", "peinture", "demi-journee"],
    accent: "sand",
    icon: "landmark",
    address: "Pont-Aven, 29930",
    website: "https://www.pontaven.fr/Office-de-Tourisme",
    bookingRequired: false,
    price: null,
    featured: false,
    heart: false,
    tip: null
  },
  {
    id: "ria-etel",
    name: "La Ria d'Étel",
    categories: ["balades", "nature", "mer"],
    description: "Une rivière marine encaissée qui se découvre à pied le long de ses rives, entre le village de Nostang et la Barre d'Étel — marées, îlots et lumière changeante.",
    distance: "≈ 28 km",
    driveTime: "35 min en voiture",
    duration: "2h à demi-journée",
    tags: ["balade", "nature", "randonnee", "maree", "demi-journee"],
    accent: "ocean",
    icon: "wave",
    address: "Étel / Nostang, 56550",
    website: "https://www.lorientbretagnesudtourisme.fr/fr/aux-alentours/cote-morbihan/ria-d-etel/",
    bookingRequired: false,
    price: null,
    featured: false,
    heart: false,
    tip: null
  },
  {
    id: "saint-cado",
    name: "Saint-Cado",
    categories: ["patrimoine", "balades", "incontournables"],
    description: "Un îlot relié à la terre par un pont de pierre, sa chapelle romane du XIIe siècle et sa légende du diable — l'un des sites les plus photographiés du Morbihan, sur la Ria d'Étel.",
    distance: "≈ 30 km",
    driveTime: "35 min en voiture",
    duration: "1h à 2h",
    tags: ["patrimoine", "balade", "photo", "demi-journee", "incontournable"],
    accent: "sand",
    icon: "landmark",
    address: "Saint-Cado, 56550 Belz",
    website: "https://morbihan.com/a-voir-a-faire/suivez-le-guide/chapelle-saint-cado-belz-fr-6094584/",
    bookingRequired: false,
    price: null,
    featured: true,
    heart: true,
    tip: "Notre conseil : garez-vous près du pont et faites le tour de l'îlot à pied, comptez environ une heure."
  },
  {
    id: "larmor-plage",
    name: "Larmor-Plage",
    categories: ["mer", "famille"],
    description: "Station balnéaire familiale face à l'île de Groix, avec ses plages, la promenade du Port-Maria et son casino — à deux pas de Lorient.",
    distance: "≈ 20 km",
    driveTime: "30 min en voiture",
    duration: "Demi-journée",
    tags: ["mer", "plage", "famille", "demi-journee"],
    accent: "ocean",
    icon: "wave",
    address: "Larmor-Plage, 56260",
    website: "https://www.lorientbretagnesudtourisme.fr/fr/immanquables/larmor-plage/",
    bookingRequired: false,
    price: null,
    featured: false,
    heart: false,
    tip: null
  },
  {
    id: "guidel-plages",
    name: "Guidel-Plages & la Laïta",
    categories: ["mer", "balades", "nature", "sport"],
    description: "5 km de plages de sable à l'embouchure de la Laïta, et un sentier de 11 km le long de la rivière jusqu'au vieux moulin à marée — hérons, aigrettes et parfois une loutre.",
    distance: "≈ 25 km",
    driveTime: "35 min en voiture",
    duration: "Demi-journée",
    tags: ["mer", "plage", "balade", "nature", "surf", "demi-journee"],
    accent: "moss",
    icon: "leaf",
    address: "Guidel-Plages, 56520",
    website: "https://www.lorientbretagnesudtourisme.fr/fr/immanquables/guidel/",
    bookingRequired: false,
    price: null,
    featured: false,
    heart: false,
    tip: null
  },
  {
    id: "vallee-du-blavet",
    name: "La voie verte de la vallée du Blavet",
    categories: ["balades", "sport", "nature", "famille"],
    description: "58 km de chemin de halage plat entre Hennebont et Pontivy, à parcourir à pied, à vélo ou même en bateau électrique — un itinéraire sans dénivelé, au calme, ponctué d'écluses.",
    distance: "≈ 20 km jusqu'à Hennebont",
    driveTime: "25 min en voiture",
    duration: "2h à une journée",
    tags: ["balade", "velo", "nature", "famille", "sport", "journee"],
    accent: "moss",
    icon: "bike",
    address: "Chemin de halage, 56700 Hennebont",
    website: "https://morbihan.com/decouvrir/sauvage-mythique/sur-les-chemins-du-morbihan-balades-et-randos/idee-balade-decouverte-de-la-vallee-du-blavet/",
    bookingRequired: false,
    price: null,
    featured: false,
    heart: false,
    tip: null
  },
  {
    id: "plouhinec-dunes",
    name: "Les dunes de Plouhinec",
    categories: ["mer", "nature", "balades"],
    description: "Le prolongement des dunes sauvages de Gâvres, entre la Ria d'Étel et l'océan — sentiers côtiers, flore dunaire et grands espaces au calme.",
    distance: "≈ 18 km",
    driveTime: "25 min en voiture",
    duration: "2h à demi-journée",
    tags: ["mer", "nature", "dune", "balade", "randonnee"],
    accent: "ocean",
    icon: "wave",
    address: "Plouhinec, 56680",
    website: "https://morbihan.com/decouvrir/le-morbihan-et-ses-perles-bretonnes/destination-ria-detel/plouhinec/",
    bookingRequired: false,
    price: null,
    featured: false,
    heart: false,
    tip: null
  },
  {
    id: "reserve-pen-mane",
    name: "Réserve naturelle des marais de Pen Mané",
    categories: ["nature", "balades", "famille"],
    description: "Une réserve de vasières et prairies humides à Locmiquélic, tout près de la maison, où se croisent 150 à 200 espèces d'oiseaux — plateforme d'observation et tables de lecture du paysage.",
    distance: "≈ 6 km",
    driveTime: "10 min en voiture",
    duration: "1h à 2h",
    tags: ["nature", "oiseaux", "balade", "famille", "calme"],
    accent: "moss",
    icon: "leaf",
    address: "Marais de Pen Mané, 56570 Locmiquélic",
    website: "https://www.lorientbretagnesudtourisme.fr/fr/immanquables/locmiquelic/reserve-marais-pen-mane/",
    bookingRequired: false,
    price: null,
    featured: false,
    heart: true,
    tip: "Notre conseil : emportez des jumelles — la réserve ornithologique de Riantec, le long de la Petite Mer de Gâvres, complète parfaitement la visite."
  }
];

/* Parcours / expériences prêts à l'emploi — timelines éditoriales.
   Chaque étape peut référencer un id d'ACTIVITIES (activityId) pour être
   reliée à sa fiche, ou rester un simple point libre (repas, retour...). */
const EXPERIENCES = [
  {
    id: "mer-patrimoine",
    title: "Une journée entre mer & patrimoine",
    mood: ["culture", "mer"],
    who: ["couple", "famille", "solo"],
    steps: [
      { time: "08h30", label: "Petit-déjeuner à Mon Petit Coin de Bretagne" },
      { time: "10h00", label: "Balade autour de la Petite Mer de Gâvres", activityId: "petite-mer-gavres" },
      { time: "12h30", label: "Déjeuner à Port-Louis" },
      { time: "14h30", label: "Visite de la Citadelle de Port-Louis", activityId: "citadelle-port-louis" },
      { time: "16h30", label: "Après-midi plage", activityId: "grande-plage-port-louis" },
      { time: "19h00", label: "Retour à la maison" }
    ]
  },
  {
    id: "romantique",
    title: "Escapade romantique à deux",
    mood: ["detente", "mer"],
    who: ["couple"],
    steps: [
      { time: "09h00", label: "Petit-déjeuner tranquille en véranda" },
      { time: "10h30", label: "Balade sur la Petite Mer de Gâvres", activityId: "petite-mer-gavres" },
      { time: "13h00", label: "Déjeuner à Port-Louis" },
      { time: "15h00", label: "Route vers la Côte Sauvage de Quiberon", activityId: "quiberon" },
      { time: "18h30", label: "Retour à la maison, soirée piscine intérieure" }
    ]
  },
  {
    id: "famille",
    title: "Une journée en famille",
    mood: ["famille", "mer"],
    who: ["famille"],
    steps: [
      { time: "09h00", label: "Petit-déjeuner à la maison" },
      { time: "10h00", label: "Matinée plage à Fort-Bloqué", activityId: "fort-bloque" },
      { time: "12h30", label: "Pique-nique ou déjeuner sur place" },
      { time: "14h30", label: "Cité de la Voile Éric Tabarly", activityId: "cite-voile-tabarly" },
      { time: "17h30", label: "Retour à la maison, jardin et piscine" }
    ]
  },
  {
    id: "lorient",
    title: "Découvrir Lorient en une journée",
    mood: ["culture"],
    who: ["couple", "famille", "solo"],
    steps: [
      { time: "09h30", label: "Départ pour Lorient La Base" },
      { time: "10h00", label: "Cité de la Voile Éric Tabarly", activityId: "cite-voile-tabarly" },
      { time: "12h30", label: "Déjeuner à Lorient La Base" },
      { time: "14h00", label: "Base des sous-marins de Keroman", activityId: "base-keroman" },
      { time: "16h00", label: "Flânerie sur le port et retour" }
    ]
  },
  {
    id: "groix",
    title: "Une journée sur l'Île de Groix",
    mood: ["nature", "mer"],
    who: ["couple", "famille", "solo"],
    steps: [
      { time: "07h30", label: "Petit-déjeuner tôt et départ pour Lorient" },
      { time: "09h00", label: "Traversée en bateau vers Groix", activityId: "ile-de-groix" },
      { time: "10h00", label: "Tour de l'île à vélo ou à pied" },
      { time: "13h00", label: "Déjeuner à Port-Tudy" },
      { time: "18h00", label: "Retour à Lorient puis à la maison" }
    ]
  },
  {
    id: "carnac-quiberon",
    title: "Carnac & Quiberon",
    mood: ["culture", "mer"],
    who: ["couple", "famille", "solo"],
    steps: [
      { time: "09h00", label: "Départ pour Carnac" },
      { time: "10h00", label: "Visite des alignements mégalithiques", activityId: "carnac" },
      { time: "12h30", label: "Déjeuner à Carnac" },
      { time: "14h30", label: "Presqu'île de Quiberon et Côte Sauvage", activityId: "quiberon" },
      { time: "19h00", label: "Retour à la maison" }
    ]
  },
  {
    id: "pluie",
    title: "Programme pour une journée pluvieuse",
    mood: ["culture"],
    who: ["couple", "famille", "solo"],
    steps: [
      { time: "09h30", label: "Petit-déjeuner sans se presser" },
      { time: "11h00", label: "Musées de la Citadelle de Port-Louis", activityId: "citadelle-port-louis" },
      { time: "13h00", label: "Déjeuner au chaud à Port-Louis" },
      { time: "15h00", label: "Base des sous-marins de Keroman", activityId: "base-keroman" },
      { time: "18h00", label: "Retour à la maison, piscine intérieure chauffée" }
    ]
  }
];
